// <auto-generated />
using System;
using MadrasaAccounting.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MadrasaAccounting.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MadrasaDbContext))]
    partial class MadrasaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MadrasaAccounting.Domain.Entities.Admin", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<bool>("IsActive")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("boolean")
                    .HasDefaultValue(true);

                b.Property<DateTime?>("LastLogin")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Username")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.HasKey("Id");

                b.HasIndex("Email")
                    .IsUnique();

                b.HasIndex("Username")
                    .IsUnique();

                b.ToTable("Admins");
            });

            modelBuilder.Entity("MadrasaAccounting.Domain.Entities.AuditLog", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("ActionType")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<Guid>("AdminId")
                    .HasColumnType("uuid");

                b.Property<string>("Description")
                    .HasMaxLength(1000)
                    .HasColumnType("character varying(1000)");

                b.Property<string>("IpAddress")
                    .HasMaxLength(45)
                    .HasColumnType("character varying(45)");

                b.Property<string>("NewValues")
                    .HasColumnType("jsonb");

                b.Property<string>("OldValues")
                    .HasColumnType("jsonb");

                b.Property<DateTime>("Timestamp")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid?>("TransactionId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("ActionType");

                b.HasIndex("AdminId", "Timestamp");

                b.ToTable("AuditLogs");
            });

            modelBuilder.Entity("MadrasaAccounting.Domain.Entities.Expense", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<decimal>("Amount")
                    .HasPrecision(18, 2)
                    .HasColumnType("numeric(18,2)");

                b.Property<Guid>("AdminId")
                    .HasColumnType("uuid");

                b.Property<Guid>("CategoryId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("Date")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Description")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<string>("PaymentMethod")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("AdminId", "Date");

                b.HasIndex("CategoryId");

                b.ToTable("Expenses");

                b.HasCheckConstraint("CK_Expense_Amount_Positive", "\"Amount\" > 0");
            });

            modelBuilder.Entity("MadrasaAccounting.Domain.Entities.ExpenseCategory", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("AdminId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<bool>("IsDefault")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("boolean")
                    .HasDefaultValue(false);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.HasKey("Id");

                b.HasIndex("AdminId", "Name")
                    .IsUnique();

                b.ToTable("ExpenseCategories");
            });

            modelBuilder.Entity("MadrasaAccounting.Domain.Entities.Income", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<decimal>("Amount")
                    .HasPrecision(18, 2)
                    .HasColumnType("numeric(18,2)");

                b.Property<Guid>("AdminId")
                    .HasColumnType("uuid");

                b.Property<Guid>("CategoryId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("Date")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Description")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<string>("PaymentMethod")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("AdminId", "Date");

                b.HasIndex("CategoryId");

                b.ToTable("Incomes");

                b.HasCheckConstraint("CK_Income_Amount_Positive", "\"Amount\" > 0");
            });

            modelBuilder.Entity("MadrasaAccounting.Domain.Entities.IncomeCategory", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("AdminId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<bool>("IsDefault")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("boolean")
                    .HasDefaultValue(false);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.HasKey("Id");

                b.HasIndex("AdminId", "Name")
                    .IsUnique();

                b.ToTable("IncomeCategories");
            });

            modelBuilder.Entity("MadrasaAccounting.Domain.Entities.Settings", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("AdminId")
                    .HasColumnType("uuid");

                b.Property<string>("Address")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Currency")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(3)
                    .HasColumnType("character varying(3)")
                    .HasDefaultValue("AED");

                b.Property<DateTime?>("FinancialYearStart")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("LogoPath")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<string>("MadrasaName")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<string>("Phone")
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("AdminId")
                    .IsUnique();

                b.ToTable("Settings");
            });

            modelBuilder.Entity("MadrasaAccounting.Domain.Entities.AuditLog", b =>
            {
                b.HasOne("MadrasaAccounting.Domain.Entities.Admin", "Admin")
                    .WithMany()
                    .HasForeignKey("AdminId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Admin");
            });

            modelBuilder.Entity("MadrasaAccounting.Domain.Entities.Expense", b =>
            {
                b.HasOne("MadrasaAccounting.Domain.Entities.Admin", "Admin")
                    .WithMany()
                    .HasForeignKey("AdminId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("MadrasaAccounting.Domain.Entities.ExpenseCategory", "Category")
                    .WithMany()
                    .HasForeignKey("CategoryId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Admin");
                b.Navigation("Category");
            });

            modelBuilder.Entity("MadrasaAccounting.Domain.Entities.ExpenseCategory", b =>
            {
                b.HasOne("MadrasaAccounting.Domain.Entities.Admin", "Admin")
                    .WithMany()
                    .HasForeignKey("AdminId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Admin");
            });

            modelBuilder.Entity("MadrasaAccounting.Domain.Entities.Income", b =>
            {
                b.HasOne("MadrasaAccounting.Domain.Entities.Admin", "Admin")
                    .WithMany()
                    .HasForeignKey("AdminId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("MadrasaAccounting.Domain.Entities.IncomeCategory", "Category")
                    .WithMany()
                    .HasForeignKey("CategoryId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Admin");
                b.Navigation("Category");
            });

            modelBuilder.Entity("MadrasaAccounting.Domain.Entities.IncomeCategory", b =>
            {
                b.HasOne("MadrasaAccounting.Domain.Entities.Admin", "Admin")
                    .WithMany()
                    .HasForeignKey("AdminId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Admin");
            });

            modelBuilder.Entity("MadrasaAccounting.Domain.Entities.Settings", b =>
            {
                b.HasOne("MadrasaAccounting.Domain.Entities.Admin", "Admin")
                    .WithMany()
                    .HasForeignKey("AdminId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Admin");
            });
#pragma warning restore 612, 618
        }
    }
}
