-- AlterTable
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "financialYearEnd" INTEGER NOT NULL DEFAULT 12;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "website" TEXT;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "taxId" TEXT;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "registrationNumber" TEXT;
